### ISSUE TITLE
jipcode 2.0への対応

### ISSUE THREAD

**Issue by jkr2255** [oieioi/jipcode-address_locator#2]
数日前にjipcode 2.0がリリースされていました。

新バージョンではRubyのバージョン範囲が変わった程度で、おそらくjipcode-address_locatorもそのまま動かせるものと思われます。

jipcodeのバージョン範囲を広げてもらえると助かります。

**Comment by oieioi** [comment]
@jkr2255 
ご報告ありがとうございます。
そのままテスト通ったので jipcode のバージョンを `~>1.5.0` から `>=1.5.0` として、 v0.1.1 としてリリースしました。
