### ISSUE TITLE
jipcode 3.0への対応

### ISSUE THREAD

**Issue by jkr2255** [oieioi/jipcode-address_locator#3]
jipcode 3.0ではフリガナのデータも盛り込まれ、[CSVファイルも列が増えて形式が変化しています](https://github.com/rinkei/jipcode/blob/master/zipcode/latest/001.csv)。

現行のインデクサでは新形式のCSVに対応できませんので、ご対応いただけましたら幸いです。

**Comment by oieioi** [comment]
@jkr2255 
お知らせありがとうございます。
3.0.0 として jipcode v3系の対応を行いました。
https://rubygems.org/gems/jipcode-address_locator/versions/3.0.0
